import SearchInput from "./searchInput";

export const metadata = {
    title: 'Item List',
    description: 'Generated by create next app',
}

interface LayoutProps {
    children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({
    children,
}) => {
    return ( 
        <div className="flex min-h-screen w-full flex-col bg-muted/40">
        <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
            <SearchInput/>
            {children}
        </div>
        </div>
     );
}
 
export default Layout;