'use client';

import type { Metadata } from "next";
import { usePathname } from 'next/navigation'
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Toaster } from 'sonner';
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
function shouldDisableNavbar(pathname: string) {
  // Daftar rute yang harus menonaktifkan navbar
  const disableNavbarRoutes = ['/login', '/register'];

  // Cek apakah pathname adalah salah satu dari disableNavbarRoutes
  if (disableNavbarRoutes.includes(pathname)) {
    return true;
  }

  // Cek apakah pathname di bawah /api
  if (pathname.startsWith('/api')) {
    return true;
  }

  // Jika tidak ada yang cocok, jangan nonaktifkan navbar
  return false;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()
  return (
    <html lang="en">
    <SessionProvider>
    <Toaster position="top-center" richColors />
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </SessionProvider>
    </html>
  );
}
